<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PanComido.Aplicacion</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CasosDeUso\Comandos\" />
    <Folder Include="CasosDeUso\Consultas\" />
    <Folder Include="DTOs\" />
    <Folder Include="Mappers\" />
  </ItemGroup>

</Project>
