<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PanComido.Infraestructura</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Persistencia\Mappers\" />
    <Folder Include="Persistencia\Repositorios\" />
    <Folder Include="ServiciosExternos\" />
  </ItemGroup>

</Project>
