// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PanComido.Infraestructura.Persistencia;

#nullable disable

namespace PanComido.Infraestructura.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610014734_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArticuloConfiguracionArticulo", b =>
                {
                    b.Property<int>("ArticuloId")
                        .HasColumnType("integer")
                        .HasColumnName("articulo_id");

                    b.Property<int>("ConfiguracionArticuloId")
                        .HasColumnType("integer")
                        .HasColumnName("configuracion_articulo_id");

                    b.HasKey("ArticuloId", "ConfiguracionArticuloId")
                        .HasName("articulo_configuracion_articulo_pkey");

                    b.HasIndex("ConfiguracionArticuloId");

                    b.ToTable("articulo_configuracion_articulo", (string)null);
                });

            modelBuilder.Entity("CategoriaInsumoProveedor", b =>
                {
                    b.Property<int>("CategoriaInsumoId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_insumo_id");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer")
                        .HasColumnName("proveedor_id");

                    b.HasKey("CategoriaInsumoId", "ProveedorId")
                        .HasName("categoria_insumo_proveedor_pkey");

                    b.HasIndex("ProveedorId");

                    b.ToTable("categoria_insumo_proveedor", (string)null);
                });

            modelBuilder.Entity("EmpleadoTurnoLaboral", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer")
                        .HasColumnName("empleado_id");

                    b.Property<int>("TurnoLaboralId")
                        .HasColumnType("integer")
                        .HasColumnName("turno_laboral_id");

                    b.HasKey("EmpleadoId", "TurnoLaboralId")
                        .HasName("empleado_turno_laboral_pkey");

                    b.HasIndex("TurnoLaboralId");

                    b.ToTable("empleado_turno_laboral", (string)null);
                });

            modelBuilder.Entity("MesaMozo", b =>
                {
                    b.Property<int>("MesaId")
                        .HasColumnType("integer");

                    b.Property<int>("MozoId")
                        .HasColumnType("integer");

                    b.HasKey("MesaId", "MozoId");

                    b.ToTable("MesaMozo");
                });

            modelBuilder.Entity("MozoMesa", b =>
                {
                    b.Property<int>("MozoId")
                        .HasColumnType("integer")
                        .HasColumnName("mozo_id");

                    b.Property<int>("MesaId")
                        .HasColumnType("integer")
                        .HasColumnName("mesa_id");

                    b.HasKey("MozoId", "MesaId")
                        .HasName("mozo_mesa_pkey");

                    b.HasIndex("MesaId");

                    b.ToTable("mozo_mesa", (string)null);
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartaId")
                        .HasColumnType("integer")
                        .HasColumnName("carta_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PrecioGanancia")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_ganancia");

                    b.Property<decimal?>("PrecioPromocional")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_promocional");

                    b.Property<decimal?>("PrecioVentaFinal")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_venta_final");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurante_id");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("text")
                        .HasColumnName("url_imagen");

                    b.HasKey("Id")
                        .HasName("articulo_pkey");

                    b.HasIndex("CartaId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("articulo");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.ArticuloComandum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("integer")
                        .HasColumnName("articulo_id");

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("cantidad");

                    b.Property<int>("ComandaId")
                        .HasColumnType("integer")
                        .HasColumnName("comanda_id");

                    b.Property<bool>("Entregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("entregado");

                    b.Property<string>("ObservacionesGenerales")
                        .HasColumnType("text")
                        .HasColumnName("observaciones_generales");

                    b.Property<string>("ObservacionesIngrediente")
                        .HasColumnType("text")
                        .HasColumnName("observaciones_ingrediente");

                    b.HasKey("Id")
                        .HasName("articulo_comanda_pkey");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("ComandaId");

                    b.ToTable("articulo_comanda");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Bodega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurante_id");

                    b.Property<int>("TipoBodegaId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_bodega_id");

                    b.HasKey("Id")
                        .HasName("bodega_pkey");

                    b.HasIndex("RestauranteId");

                    b.HasIndex("TipoBodegaId");

                    b.ToTable("bodega");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Cartum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurante_id");

                    b.HasKey("Id")
                        .HasName("carta_pkey");

                    b.HasIndex("RestauranteId");

                    b.ToTable("carta");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.CategoriaInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("TipoAplica")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_aplica");

                    b.HasKey("Id")
                        .HasName("categoria_insumo_pkey");

                    b.HasIndex(new[] { "Descripcion" }, "categoria_insumo_descripcion_key")
                        .IsUnique();

                    b.ToTable("categoria_insumo");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.CategoriaLlamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("categoria_llamado_pkey");

                    b.HasIndex(new[] { "Descripcion" }, "categoria_llamado_descripcion_key")
                        .IsUnique();

                    b.ToTable("categoria_llamado");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.CategoriaPlato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("categoria_plato_pkey");

                    b.HasIndex(new[] { "Descripcion" }, "categoria_plato_descripcion_key")
                        .IsUnique();

                    b.ToTable("categoria_plato");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Cierre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("numeric")
                        .HasColumnName("diferencia");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurante_id");

                    b.Property<decimal>("Sobrante")
                        .HasColumnType("numeric")
                        .HasColumnName("sobrante");

                    b.Property<int>("TurnoLaboralId")
                        .HasColumnType("integer")
                        .HasColumnName("turno_laboral_id");

                    b.HasKey("Id")
                        .HasName("cierre_pkey");

                    b.HasIndex("RestauranteId");

                    b.HasIndex("TurnoLaboralId");

                    b.ToTable("cierre");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Cocina", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.HasKey("IdEmpleado")
                        .HasName("cocina_pkey");

                    b.ToTable("cocina");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Comandum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantComensales")
                        .HasColumnType("integer")
                        .HasColumnName("cant_comensales");

                    b.Property<int>("EstadoComandaId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_comanda_id");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("hora_fin");

                    b.Property<DateTime>("HoraInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("hora_inicio")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("HoraUltimoCambioEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("hora_ultimo_cambio_estado")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MesaId")
                        .HasColumnType("integer")
                        .HasColumnName("mesa_id");

                    b.Property<int?>("PagoId")
                        .HasColumnType("integer")
                        .HasColumnName("pago_id");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurante_id");

                    b.HasKey("Id")
                        .HasName("comanda_pkey");

                    b.HasIndex("EstadoComandaId");

                    b.HasIndex("MesaId");

                    b.HasIndex("PagoId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("comanda");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.ConfiguracionArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("configuracion_articulo_pkey");

                    b.HasIndex(new[] { "Descripcion" }, "configuracion_articulo_descripcion_key")
                        .IsUnique();

                    b.ToTable("configuracion_articulo");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.DimensionMesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forma");

                    b.Property<string>("Imagen")
                        .HasColumnType("text")
                        .HasColumnName("imagen");

                    b.HasKey("Id")
                        .HasName("dimension_mesa_pkey");

                    b.ToTable("dimension_mesa");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contrasena");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'activo'::text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurante_id");

                    b.HasKey("Id")
                        .HasName("empleado_pkey");

                    b.HasIndex("RestauranteId");

                    b.ToTable("empleado");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.EstadoComandum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("estado_comanda_pkey");

                    b.HasIndex(new[] { "Descripcion" }, "estado_comanda_descripcion_key")
                        .IsUnique();

                    b.ToTable("estado_comanda");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.EstadoMesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("estado_mesa_pkey");

                    b.HasIndex(new[] { "Descripcion" }, "estado_mesa_descripcion_key")
                        .IsUnique();

                    b.ToTable("estado_mesa");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.EstadoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("estado_pedido_pkey");

                    b.HasIndex(new[] { "Descripcion" }, "estado_pedido_descripcion_key")
                        .IsUnique();

                    b.ToTable("estado_pedido");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.FilaVirtual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Habilitada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("habilitada");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurante_id");

                    b.HasKey("Id")
                        .HasName("fila_virtual_pkey");

                    b.HasIndex("RestauranteId");

                    b.ToTable("fila_virtual");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Gerente", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.HasKey("IdEmpleado")
                        .HasName("gerente_pkey");

                    b.ToTable("gerente");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Grilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantColumnas")
                        .HasColumnType("integer")
                        .HasColumnName("cant_columnas");

                    b.Property<int>("CantFilas")
                        .HasColumnType("integer")
                        .HasColumnName("cant_filas");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurante_id");

                    b.HasKey("Id")
                        .HasName("grilla_pkey");

                    b.HasIndex("RestauranteId");

                    b.ToTable("grilla");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Ingrediente", b =>
                {
                    b.Property<int>("IdInsumo")
                        .HasColumnType("integer")
                        .HasColumnName("id_insumo");

                    b.HasKey("IdInsumo")
                        .HasName("ingrediente_pkey");

                    b.ToTable("ingrediente");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.IngredienteIngredientePreparado", b =>
                {
                    b.Property<int>("IngredienteId")
                        .HasColumnType("integer")
                        .HasColumnName("ingrediente_id");

                    b.Property<int>("IngredientePreparadoId")
                        .HasColumnType("integer")
                        .HasColumnName("ingrediente_preparado_id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad");

                    b.HasKey("IngredienteId", "IngredientePreparadoId")
                        .HasName("ingrediente_ingrediente_preparado_pkey");

                    b.HasIndex("IngredientePreparadoId");

                    b.ToTable("ingrediente_ingrediente_preparado");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.IngredientePreparado", b =>
                {
                    b.Property<int>("IdIngrediente")
                        .HasColumnType("integer")
                        .HasColumnName("id_ingrediente");

                    b.HasKey("IdIngrediente")
                        .HasName("ingrediente_preparado_pkey");

                    b.ToTable("ingrediente_preparado");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Insumo", b =>
                {
                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer")
                        .HasColumnName("id_articulo");

                    b.Property<int>("CategoriaInsumoId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_insumo_id");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("numeric")
                        .HasColumnName("stock_minimo");

                    b.Property<int>("UnidadMedidaId")
                        .HasColumnType("integer")
                        .HasColumnName("unidad_medida_id");

                    b.HasKey("IdArticulo")
                        .HasName("insumo_pkey");

                    b.HasIndex("CategoriaInsumoId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("insumo");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Llamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaLlamadoId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_llamado_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int?>("GerenteId")
                        .HasColumnType("integer")
                        .HasColumnName("gerente_id");

                    b.Property<int?>("MesaId")
                        .HasColumnType("integer")
                        .HasColumnName("mesa_id");

                    b.Property<int?>("MozoId")
                        .HasColumnType("integer")
                        .HasColumnName("mozo_id");

                    b.Property<bool>("Resuelto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("resuelto");

                    b.HasKey("Id")
                        .HasName("llamado_pkey");

                    b.HasIndex("CategoriaLlamadoId");

                    b.HasIndex("GerenteId");

                    b.HasIndex("MesaId");

                    b.HasIndex("MozoId");

                    b.ToTable("llamado");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BodegaId")
                        .HasColumnType("integer")
                        .HasColumnName("bodega_id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad");

                    b.Property<DateOnly>("FechaAdquisicion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_adquisicion");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("InsumoId")
                        .HasColumnType("integer")
                        .HasColumnName("insumo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("lote_pkey");

                    b.HasIndex("BodegaId");

                    b.HasIndex("InsumoId");

                    b.ToTable("lote");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantPersonasMax")
                        .HasColumnType("integer")
                        .HasColumnName("cant_personas_max");

                    b.Property<string>("CodigoInvitacion")
                        .HasColumnType("text")
                        .HasColumnName("codigo_invitacion");

                    b.Property<int>("DimensionMesaId")
                        .HasColumnType("integer")
                        .HasColumnName("dimension_mesa_id");

                    b.Property<int>("EstadoMesaId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_mesa_id");

                    b.Property<int>("GrillaId")
                        .HasColumnType("integer")
                        .HasColumnName("grilla_id");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<int>("PosicionXFin")
                        .HasColumnType("integer")
                        .HasColumnName("posicion_x_fin");

                    b.Property<int>("PosicionXInicio")
                        .HasColumnType("integer")
                        .HasColumnName("posicion_x_inicio");

                    b.Property<int>("PosicionYFin")
                        .HasColumnType("integer")
                        .HasColumnName("posicion_y_fin");

                    b.Property<int>("PosicionYInicio")
                        .HasColumnType("integer")
                        .HasColumnName("posicion_y_inicio");

                    b.HasKey("Id")
                        .HasName("mesa_pkey");

                    b.HasIndex("DimensionMesaId");

                    b.HasIndex("EstadoMesaId");

                    b.HasIndex("GrillaId");

                    b.ToTable("mesa");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.MetodoDePago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("metodo_de_pago_pkey");

                    b.HasIndex(new[] { "Descripcion" }, "metodo_de_pago_descripcion_key")
                        .IsUnique();

                    b.ToTable("metodo_de_pago");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.MetodoDePagoRestaurante", b =>
                {
                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurante_id");

                    b.Property<int>("MetodoDePagoId")
                        .HasColumnType("integer")
                        .HasColumnName("metodo_de_pago_id");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("habilitado");

                    b.HasKey("RestauranteId", "MetodoDePagoId")
                        .HasName("metodo_de_pago_restaurante_pkey");

                    b.HasIndex("MetodoDePagoId");

                    b.ToTable("metodo_de_pago_restaurante");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Mozo", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.HasKey("IdEmpleado")
                        .HasName("mozo_pkey");

                    b.ToTable("mozo");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurante_id");

                    b.Property<bool>("Resuelta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("resuelta");

                    b.HasKey("Id")
                        .HasName("notificacion_pkey");

                    b.HasIndex("RestauranteId");

                    b.ToTable("notificacion");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CierreId")
                        .HasColumnType("integer")
                        .HasColumnName("cierre_id");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("integer")
                        .HasColumnName("metodo_pago_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pago_pkey");

                    b.HasIndex("CierreId");

                    b.HasIndex("MetodoPagoId");

                    b.ToTable("pago");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoPedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_pedido_id");

                    b.Property<DateOnly>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer")
                        .HasColumnName("proveedor_id");

                    b.HasKey("Id")
                        .HasName("pedido_pkey");

                    b.HasIndex("EstadoPedidoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("pedido");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.PedidoInsumo", b =>
                {
                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<int>("InsumoId")
                        .HasColumnType("integer")
                        .HasColumnName("insumo_id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_compra");

                    b.HasKey("PedidoId", "InsumoId")
                        .HasName("pedido_insumo_pkey");

                    b.HasIndex("InsumoId");

                    b.ToTable("pedido_insumo");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Plato", b =>
                {
                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer")
                        .HasColumnName("id_articulo");

                    b.Property<int>("CategoriaPlatoId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_plato_id");

                    b.Property<bool>("Destacado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("destacado");

                    b.Property<bool>("Sugerencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sugerencia");

                    b.Property<int>("TiempoPreparacionBase")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_preparacion_base");

                    b.Property<int>("TipoPlatoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_plato_id");

                    b.HasKey("IdArticulo")
                        .HasName("plato_pkey");

                    b.HasIndex("CategoriaPlatoId");

                    b.HasIndex("TipoPlatoId");

                    b.ToTable("plato");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.PlatoIngrediente", b =>
                {
                    b.Property<int>("PlatoId")
                        .HasColumnType("integer")
                        .HasColumnName("plato_id");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("integer")
                        .HasColumnName("ingrediente_id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad");

                    b.Property<bool>("Opcional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("opcional");

                    b.HasKey("PlatoId", "IngredienteId")
                        .HasName("plato_ingrediente_pkey");

                    b.HasIndex("IngredienteId");

                    b.ToTable("plato_ingrediente");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroTelefonoWsp")
                        .HasColumnType("text")
                        .HasColumnName("numero_telefono_wsp");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurante_id");

                    b.HasKey("Id")
                        .HasName("proveedor_pkey");

                    b.HasIndex("RestauranteId");

                    b.ToTable("proveedor");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantComensales")
                        .HasColumnType("integer")
                        .HasColumnName("cant_comensales");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeOnly>("Horario")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario");

                    b.Property<int>("MesaId")
                        .HasColumnType("integer")
                        .HasColumnName("mesa_id");

                    b.Property<string>("NombreTitular")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_titular");

                    b.Property<string>("TelContacto")
                        .HasColumnType("text")
                        .HasColumnName("tel_contacto");

                    b.HasKey("Id")
                        .HasName("reserva_pkey");

                    b.HasIndex("MesaId");

                    b.ToTable("reserva");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorPrincipal")
                        .HasColumnType("text")
                        .HasColumnName("color_principal");

                    b.Property<string>("ColorSecundario")
                        .HasColumnType("text")
                        .HasColumnName("color_secundario");

                    b.Property<int>("DireccionId")
                        .HasColumnType("integer")
                        .HasColumnName("direccion_id");

                    b.Property<string>("Imagen")
                        .HasColumnType("text")
                        .HasColumnName("imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("TextoPrincipal")
                        .HasColumnType("text")
                        .HasColumnName("texto_principal");

                    b.Property<string>("TextoSecundario")
                        .HasColumnType("text")
                        .HasColumnName("texto_secundario");

                    b.HasKey("Id")
                        .HasName("restaurante_pkey");

                    b.HasIndex("DireccionId");

                    b.ToTable("restaurante");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Restriccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("restriccion_pkey");

                    b.HasIndex(new[] { "Descripcion" }, "restriccion_descripcion_key")
                        .IsUnique();

                    b.ToTable("restriccion");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.SugerenciaPlatoIum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurante_id");

                    b.HasKey("Id")
                        .HasName("sugerencia_plato_ia_pkey");

                    b.HasIndex("RestauranteId");

                    b.ToTable("sugerencia_plato_ia");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.TipoBodega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("tipo_bodega_pkey");

                    b.HasIndex(new[] { "Descripcion" }, "tipo_bodega_descripcion_key")
                        .IsUnique();

                    b.ToTable("tipo_bodega");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.TipoPlato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("tipo_plato_pkey");

                    b.HasIndex(new[] { "Descripcion" }, "tipo_plato_descripcion_key")
                        .IsUnique();

                    b.ToTable("tipo_plato");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.TurnoFila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FilaVirtualId")
                        .HasColumnType("integer")
                        .HasColumnName("fila_virtual_id");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("turno_fila_pkey");

                    b.HasIndex("FilaVirtualId");

                    b.ToTable("turno_fila");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.TurnoLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("HorarioLaboralFin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario_laboral_fin");

                    b.Property<TimeOnly>("HorarioLaboralInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario_laboral_inicio");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurante_id");

                    b.HasKey("Id")
                        .HasName("turno_laboral_pkey");

                    b.HasIndex("RestauranteId");

                    b.ToTable("turno_laboral");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.HasKey("Id")
                        .HasName("ubicacion_pkey");

                    b.ToTable("ubicacion");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.UnidadMedidum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("unidad_medida_pkey");

                    b.HasIndex(new[] { "Nombre" }, "unidad_medida_nombre_key")
                        .IsUnique();

                    b.ToTable("unidad_medida");
                });

            modelBuilder.Entity("PlatoRestriccion", b =>
                {
                    b.Property<int>("PlatoId")
                        .HasColumnType("integer");

                    b.Property<int>("RestriccionId")
                        .HasColumnType("integer");

                    b.HasKey("PlatoId", "RestriccionId");

                    b.ToTable("PlatoRestriccion");
                });

            modelBuilder.Entity("RestriccionPlato", b =>
                {
                    b.Property<int>("RestriccionId")
                        .HasColumnType("integer")
                        .HasColumnName("restriccion_id");

                    b.Property<int>("PlatoId")
                        .HasColumnType("integer")
                        .HasColumnName("plato_id");

                    b.HasKey("RestriccionId", "PlatoId")
                        .HasName("restriccion_plato_pkey");

                    b.HasIndex("PlatoId");

                    b.ToTable("restriccion_plato", (string)null);
                });

            modelBuilder.Entity("ArticuloConfiguracionArticulo", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Articulo", null)
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .IsRequired()
                        .HasConstraintName("articulo_configuracion_articulo_articulo_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.ConfiguracionArticulo", null)
                        .WithMany()
                        .HasForeignKey("ConfiguracionArticuloId")
                        .IsRequired()
                        .HasConstraintName("articulo_configuracion_articulo_configuracion_articulo_id_fkey");
                });

            modelBuilder.Entity("CategoriaInsumoProveedor", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.CategoriaInsumo", null)
                        .WithMany()
                        .HasForeignKey("CategoriaInsumoId")
                        .IsRequired()
                        .HasConstraintName("categoria_insumo_proveedor_categoria_insumo_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .IsRequired()
                        .HasConstraintName("categoria_insumo_proveedor_proveedor_id_fkey");
                });

            modelBuilder.Entity("EmpleadoTurnoLaboral", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Empleado", null)
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("empleado_turno_laboral_empleado_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.TurnoLaboral", null)
                        .WithMany()
                        .HasForeignKey("TurnoLaboralId")
                        .IsRequired()
                        .HasConstraintName("empleado_turno_laboral_turno_laboral_id_fkey");
                });

            modelBuilder.Entity("MozoMesa", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Mesa", null)
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .IsRequired()
                        .HasConstraintName("mozo_mesa_mesa_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Mozo", null)
                        .WithMany()
                        .HasForeignKey("MozoId")
                        .IsRequired()
                        .HasConstraintName("mozo_mesa_mozo_id_fkey");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Articulo", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Cartum", "Carta")
                        .WithMany("Articulos")
                        .HasForeignKey("CartaId")
                        .HasConstraintName("articulo_carta_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", "Restaurante")
                        .WithMany("Articulos")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("articulo_restaurante_id_fkey");

                    b.Navigation("Carta");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.ArticuloComandum", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Articulo", "Articulo")
                        .WithMany("ArticuloComanda")
                        .HasForeignKey("ArticuloId")
                        .IsRequired()
                        .HasConstraintName("articulo_comanda_articulo_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Comandum", "Comanda")
                        .WithMany("ArticuloComanda")
                        .HasForeignKey("ComandaId")
                        .IsRequired()
                        .HasConstraintName("articulo_comanda_comanda_id_fkey");

                    b.Navigation("Articulo");

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Bodega", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", "Restaurante")
                        .WithMany("Bodegas")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("bodega_restaurante_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.TipoBodega", "TipoBodega")
                        .WithMany("Bodegas")
                        .HasForeignKey("TipoBodegaId")
                        .IsRequired()
                        .HasConstraintName("bodega_tipo_bodega_id_fkey");

                    b.Navigation("Restaurante");

                    b.Navigation("TipoBodega");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Cartum", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", "Restaurante")
                        .WithMany("Carta")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("carta_restaurante_id_fkey");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Cierre", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", "Restaurante")
                        .WithMany("Cierres")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("cierre_restaurante_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.TurnoLaboral", "TurnoLaboral")
                        .WithMany("Cierres")
                        .HasForeignKey("TurnoLaboralId")
                        .IsRequired()
                        .HasConstraintName("cierre_turno_laboral_id_fkey");

                    b.Navigation("Restaurante");

                    b.Navigation("TurnoLaboral");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Cocina", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Empleado", "IdEmpleadoNavigation")
                        .WithOne("Cocina")
                        .HasForeignKey("PanComido.Infraestructura.Persistencia.Entidades.Cocina", "IdEmpleado")
                        .IsRequired()
                        .HasConstraintName("cocina_id_empleado_fkey");

                    b.Navigation("IdEmpleadoNavigation");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Comandum", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.EstadoComandum", "EstadoComanda")
                        .WithMany("Comanda")
                        .HasForeignKey("EstadoComandaId")
                        .IsRequired()
                        .HasConstraintName("comanda_estado_comanda_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Mesa", "Mesa")
                        .WithMany("Comanda")
                        .HasForeignKey("MesaId")
                        .IsRequired()
                        .HasConstraintName("comanda_mesa_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Pago", "Pago")
                        .WithMany("Comanda")
                        .HasForeignKey("PagoId")
                        .HasConstraintName("comanda_pago_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", "Restaurante")
                        .WithMany("Comanda")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("comanda_restaurante_id_fkey");

                    b.Navigation("EstadoComanda");

                    b.Navigation("Mesa");

                    b.Navigation("Pago");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Empleado", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", "Restaurante")
                        .WithMany("Empleados")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("empleado_restaurante_id_fkey");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.FilaVirtual", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", "Restaurante")
                        .WithMany("FilaVirtuals")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("fila_virtual_restaurante_id_fkey");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Gerente", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Empleado", "IdEmpleadoNavigation")
                        .WithOne("Gerente")
                        .HasForeignKey("PanComido.Infraestructura.Persistencia.Entidades.Gerente", "IdEmpleado")
                        .IsRequired()
                        .HasConstraintName("gerente_id_empleado_fkey");

                    b.Navigation("IdEmpleadoNavigation");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Grilla", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", "Restaurante")
                        .WithMany("Grillas")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("grilla_restaurante_id_fkey");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Ingrediente", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Insumo", "IdInsumoNavigation")
                        .WithOne("Ingrediente")
                        .HasForeignKey("PanComido.Infraestructura.Persistencia.Entidades.Ingrediente", "IdInsumo")
                        .IsRequired()
                        .HasConstraintName("ingrediente_id_insumo_fkey");

                    b.Navigation("IdInsumoNavigation");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.IngredienteIngredientePreparado", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Ingrediente", "Ingrediente")
                        .WithMany("IngredienteIngredientePreparados")
                        .HasForeignKey("IngredienteId")
                        .IsRequired()
                        .HasConstraintName("ingrediente_ingrediente_preparado_ingrediente_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.IngredientePreparado", "IngredientePreparado")
                        .WithMany("IngredienteIngredientePreparados")
                        .HasForeignKey("IngredientePreparadoId")
                        .IsRequired()
                        .HasConstraintName("ingrediente_ingrediente_preparado_ingrediente_preparado_id_fkey");

                    b.Navigation("Ingrediente");

                    b.Navigation("IngredientePreparado");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.IngredientePreparado", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Ingrediente", "IdIngredienteNavigation")
                        .WithOne("IngredientePreparado")
                        .HasForeignKey("PanComido.Infraestructura.Persistencia.Entidades.IngredientePreparado", "IdIngrediente")
                        .IsRequired()
                        .HasConstraintName("ingrediente_preparado_id_ingrediente_fkey");

                    b.Navigation("IdIngredienteNavigation");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Insumo", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.CategoriaInsumo", "CategoriaInsumo")
                        .WithMany("Insumos")
                        .HasForeignKey("CategoriaInsumoId")
                        .IsRequired()
                        .HasConstraintName("insumo_categoria_insumo_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Articulo", "IdArticuloNavigation")
                        .WithOne("Insumo")
                        .HasForeignKey("PanComido.Infraestructura.Persistencia.Entidades.Insumo", "IdArticulo")
                        .IsRequired()
                        .HasConstraintName("insumo_id_articulo_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.UnidadMedidum", "UnidadMedida")
                        .WithMany("Insumos")
                        .HasForeignKey("UnidadMedidaId")
                        .IsRequired()
                        .HasConstraintName("insumo_unidad_medida_id_fkey");

                    b.Navigation("CategoriaInsumo");

                    b.Navigation("IdArticuloNavigation");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Llamado", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.CategoriaLlamado", "CategoriaLlamado")
                        .WithMany("Llamados")
                        .HasForeignKey("CategoriaLlamadoId")
                        .IsRequired()
                        .HasConstraintName("llamado_categoria_llamado_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Gerente", "Gerente")
                        .WithMany("Llamados")
                        .HasForeignKey("GerenteId")
                        .HasConstraintName("llamado_gerente_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Mesa", "Mesa")
                        .WithMany("Llamados")
                        .HasForeignKey("MesaId")
                        .HasConstraintName("llamado_mesa_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Mozo", "Mozo")
                        .WithMany("Llamados")
                        .HasForeignKey("MozoId")
                        .HasConstraintName("llamado_mozo_id_fkey");

                    b.Navigation("CategoriaLlamado");

                    b.Navigation("Gerente");

                    b.Navigation("Mesa");

                    b.Navigation("Mozo");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Lote", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Bodega", "Bodega")
                        .WithMany("Lotes")
                        .HasForeignKey("BodegaId")
                        .IsRequired()
                        .HasConstraintName("lote_bodega_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Insumo", "Insumo")
                        .WithMany("Lotes")
                        .HasForeignKey("InsumoId")
                        .IsRequired()
                        .HasConstraintName("lote_insumo_id_fkey");

                    b.Navigation("Bodega");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Mesa", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.DimensionMesa", "DimensionMesa")
                        .WithMany("Mesas")
                        .HasForeignKey("DimensionMesaId")
                        .IsRequired()
                        .HasConstraintName("mesa_dimension_mesa_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.EstadoMesa", "EstadoMesa")
                        .WithMany("Mesas")
                        .HasForeignKey("EstadoMesaId")
                        .IsRequired()
                        .HasConstraintName("mesa_estado_mesa_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Grilla", "Grilla")
                        .WithMany("Mesas")
                        .HasForeignKey("GrillaId")
                        .IsRequired()
                        .HasConstraintName("mesa_grilla_id_fkey");

                    b.Navigation("DimensionMesa");

                    b.Navigation("EstadoMesa");

                    b.Navigation("Grilla");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.MetodoDePagoRestaurante", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.MetodoDePago", "MetodoDePago")
                        .WithMany("MetodoDePagoRestaurantes")
                        .HasForeignKey("MetodoDePagoId")
                        .IsRequired()
                        .HasConstraintName("metodo_de_pago_restaurante_metodo_de_pago_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", "Restaurante")
                        .WithMany("MetodoDePagoRestaurantes")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("metodo_de_pago_restaurante_restaurante_id_fkey");

                    b.Navigation("MetodoDePago");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Mozo", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Empleado", "IdEmpleadoNavigation")
                        .WithOne("Mozo")
                        .HasForeignKey("PanComido.Infraestructura.Persistencia.Entidades.Mozo", "IdEmpleado")
                        .IsRequired()
                        .HasConstraintName("mozo_id_empleado_fkey");

                    b.Navigation("IdEmpleadoNavigation");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Notificacion", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", "Restaurante")
                        .WithMany("Notificacions")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("notificacion_restaurante_id_fkey");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Pago", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Cierre", "Cierre")
                        .WithMany("Pagos")
                        .HasForeignKey("CierreId")
                        .HasConstraintName("pago_cierre_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.MetodoDePago", "MetodoPago")
                        .WithMany("Pagos")
                        .HasForeignKey("MetodoPagoId")
                        .IsRequired()
                        .HasConstraintName("pago_metodo_pago_id_fkey");

                    b.Navigation("Cierre");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Pedido", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.EstadoPedido", "EstadoPedido")
                        .WithMany("Pedidos")
                        .HasForeignKey("EstadoPedidoId")
                        .IsRequired()
                        .HasConstraintName("pedido_estado_pedido_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Proveedor", "Proveedor")
                        .WithMany("Pedidos")
                        .HasForeignKey("ProveedorId")
                        .IsRequired()
                        .HasConstraintName("pedido_proveedor_id_fkey");

                    b.Navigation("EstadoPedido");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.PedidoInsumo", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Insumo", "Insumo")
                        .WithMany("PedidoInsumos")
                        .HasForeignKey("InsumoId")
                        .IsRequired()
                        .HasConstraintName("pedido_insumo_insumo_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Pedido", "Pedido")
                        .WithMany("PedidoInsumos")
                        .HasForeignKey("PedidoId")
                        .IsRequired()
                        .HasConstraintName("pedido_insumo_pedido_id_fkey");

                    b.Navigation("Insumo");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Plato", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.CategoriaPlato", "CategoriaPlato")
                        .WithMany("Platos")
                        .HasForeignKey("CategoriaPlatoId")
                        .IsRequired()
                        .HasConstraintName("plato_categoria_plato_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Articulo", "IdArticuloNavigation")
                        .WithOne("Plato")
                        .HasForeignKey("PanComido.Infraestructura.Persistencia.Entidades.Plato", "IdArticulo")
                        .IsRequired()
                        .HasConstraintName("plato_id_articulo_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.TipoPlato", "TipoPlato")
                        .WithMany("Platos")
                        .HasForeignKey("TipoPlatoId")
                        .IsRequired()
                        .HasConstraintName("plato_tipo_plato_id_fkey");

                    b.Navigation("CategoriaPlato");

                    b.Navigation("IdArticuloNavigation");

                    b.Navigation("TipoPlato");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.PlatoIngrediente", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Ingrediente", "Ingrediente")
                        .WithMany("PlatoIngredientes")
                        .HasForeignKey("IngredienteId")
                        .IsRequired()
                        .HasConstraintName("plato_ingrediente_ingrediente_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Plato", "Plato")
                        .WithMany("PlatoIngredientes")
                        .HasForeignKey("PlatoId")
                        .IsRequired()
                        .HasConstraintName("plato_ingrediente_plato_id_fkey");

                    b.Navigation("Ingrediente");

                    b.Navigation("Plato");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Proveedor", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", "Restaurante")
                        .WithMany("Proveedors")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("proveedor_restaurante_id_fkey");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Reserva", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Mesa", "Mesa")
                        .WithMany("Reservas")
                        .HasForeignKey("MesaId")
                        .IsRequired()
                        .HasConstraintName("reserva_mesa_id_fkey");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Ubicacion", "Direccion")
                        .WithMany("Restaurantes")
                        .HasForeignKey("DireccionId")
                        .IsRequired()
                        .HasConstraintName("restaurante_direccion_id_fkey");

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.SugerenciaPlatoIum", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", "Restaurante")
                        .WithMany("SugerenciaPlatoIa")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("sugerencia_plato_ia_restaurante_id_fkey");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.TurnoFila", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.FilaVirtual", "FilaVirtual")
                        .WithMany("TurnoFilas")
                        .HasForeignKey("FilaVirtualId")
                        .IsRequired()
                        .HasConstraintName("turno_fila_fila_virtual_id_fkey");

                    b.Navigation("FilaVirtual");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.TurnoLaboral", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", "Restaurante")
                        .WithMany("TurnoLaborals")
                        .HasForeignKey("RestauranteId")
                        .IsRequired()
                        .HasConstraintName("turno_laboral_restaurante_id_fkey");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("RestriccionPlato", b =>
                {
                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Plato", null)
                        .WithMany()
                        .HasForeignKey("PlatoId")
                        .IsRequired()
                        .HasConstraintName("restriccion_plato_plato_id_fkey");

                    b.HasOne("PanComido.Infraestructura.Persistencia.Entidades.Restriccion", null)
                        .WithMany()
                        .HasForeignKey("RestriccionId")
                        .IsRequired()
                        .HasConstraintName("restriccion_plato_restriccion_id_fkey");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Articulo", b =>
                {
                    b.Navigation("ArticuloComanda");

                    b.Navigation("Insumo");

                    b.Navigation("Plato");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Bodega", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Cartum", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.CategoriaInsumo", b =>
                {
                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.CategoriaLlamado", b =>
                {
                    b.Navigation("Llamados");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.CategoriaPlato", b =>
                {
                    b.Navigation("Platos");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Cierre", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Comandum", b =>
                {
                    b.Navigation("ArticuloComanda");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.DimensionMesa", b =>
                {
                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Empleado", b =>
                {
                    b.Navigation("Cocina");

                    b.Navigation("Gerente");

                    b.Navigation("Mozo");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.EstadoComandum", b =>
                {
                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.EstadoMesa", b =>
                {
                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.EstadoPedido", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.FilaVirtual", b =>
                {
                    b.Navigation("TurnoFilas");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Gerente", b =>
                {
                    b.Navigation("Llamados");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Grilla", b =>
                {
                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Ingrediente", b =>
                {
                    b.Navigation("IngredienteIngredientePreparados");

                    b.Navigation("IngredientePreparado");

                    b.Navigation("PlatoIngredientes");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.IngredientePreparado", b =>
                {
                    b.Navigation("IngredienteIngredientePreparados");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Insumo", b =>
                {
                    b.Navigation("Ingrediente");

                    b.Navigation("Lotes");

                    b.Navigation("PedidoInsumos");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Mesa", b =>
                {
                    b.Navigation("Comanda");

                    b.Navigation("Llamados");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.MetodoDePago", b =>
                {
                    b.Navigation("MetodoDePagoRestaurantes");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Mozo", b =>
                {
                    b.Navigation("Llamados");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Pago", b =>
                {
                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Pedido", b =>
                {
                    b.Navigation("PedidoInsumos");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Plato", b =>
                {
                    b.Navigation("PlatoIngredientes");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Proveedor", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Restaurante", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Bodegas");

                    b.Navigation("Carta");

                    b.Navigation("Cierres");

                    b.Navigation("Comanda");

                    b.Navigation("Empleados");

                    b.Navigation("FilaVirtuals");

                    b.Navigation("Grillas");

                    b.Navigation("MetodoDePagoRestaurantes");

                    b.Navigation("Notificacions");

                    b.Navigation("Proveedors");

                    b.Navigation("SugerenciaPlatoIa");

                    b.Navigation("TurnoLaborals");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.TipoBodega", b =>
                {
                    b.Navigation("Bodegas");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.TipoPlato", b =>
                {
                    b.Navigation("Platos");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.TurnoLaboral", b =>
                {
                    b.Navigation("Cierres");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.Ubicacion", b =>
                {
                    b.Navigation("Restaurantes");
                });

            modelBuilder.Entity("PanComido.Infraestructura.Persistencia.Entidades.UnidadMedidum", b =>
                {
                    b.Navigation("Insumos");
                });
#pragma warning restore 612, 618
        }
    }
}
