name: prueba-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ==========================================
  # JOB 1: BACKEND (.NET)
  # ==========================================
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/PanComido.Presentacion
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Caché de NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          
      - name: Restore & Test
        run: |
          dotnet restore PanComido.sln
          dotnet build PanComido.sln --no-restore -c Release
          dotnet test PanComido.sln --no-build -c Release

  # ==========================================
  # JOB 2: DEPLOY BACKEND (Azure App Service)
  # ==========================================
  deploy-backend:
    needs: [backend-tests] # Regla estricta: solo despliega si los tests pasaron
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/PanComido.Presentacion
        
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      # Opcional pero recomendado: restaurar caché de NuGet aquí también para ganar velocidad
      - name: Caché de NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}

      - name: Publish API
        # dotnet publish compila y prepara los archivos finales en la carpeta 'publish', osea los compilados
        run: dotnet publish PanComido.sln -c Release -o ./publish

      - name: Desplegar a Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-pan-comido' # El nombre del App Service en Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './backend/PanComido.Presentacion/publish' # Ruta desde la raíz del repo 